Notebook written to show the steps involved in finding the covariance matrix.

First we create some data to find the covariance matrix of.

In [23]:
x = [1,2,3,4]
y = [2,4,6,8]
z = [10,9,8,7]
data = [x,y,z]

In [24]:
import numpy as np
data = np.array(data) # converting to np array
print(data) # note that the rows correspond to the vatriables x, y z

[[ 1  2  3  4]
 [ 2  4  6  8]
 [10  9  8  7]]


In [30]:
print(np.cov(data)) # the covariance matrix

[[ 1.66666667  3.33333333 -1.66666667]
 [ 3.33333333  6.66666667 -3.33333333]
 [-1.66666667 -3.33333333  1.66666667]]


In [28]:
print(np.cov(data, bias=True)) # setting bias=True corresponds to normalization by a factor of N instead of (N-1)

[[ 1.25  2.5  -1.25]
 [ 2.5   5.   -2.5 ]
 [-1.25 -2.5   1.25]]


If $x$ is a vairable with $N$ data points (i.e. $x=\{x_1, x_2, \ldots, x_N\}$, the variance is given by $\text{var}(x)=\frac{1}{N}\sum_{i=1}^N (x_i-\mu)^2$ where $\mu=\frac{1}{N}\sum_{i=1}^N x_i$ is the mean of the variable. The variance is essentially the sum of the differences between each component and the mean squared.

In [32]:
def var(x):
    s = 0
    mu = sum(x)/len(x)
    for i in range(len(x)):
        s += (x[i] - mu)**2
    return s/len(x)

In [35]:
var(x), var(y), var(z)

(1.25, 5.0, 1.25)

If we scale the final result by $N-1$ instead of $N$, $\text{var}(x)=\frac{1}{N-1}\sum_{i=1}^N (x_i-\mu)^2$,  we get the variance with no bias.

In [36]:
def var(x):
    s = 0
    mu = sum(x)/len(x)
    for i in range(len(x)):
        s += (x[i] - mu)**2
    return s/(len(x)-1)

In [37]:
var(x), var(y), var(z)

(1.6666666666666667, 6.666666666666667, 1.6666666666666667)

# Covariance function

The covariance of two variables $x$ and $y$ is given by $\text{cov}(x,y)=\frac{1}{N}\sum_{i=1}^N (x_i-\mu_x)(y_i-\mu_y)$.

In [38]:
def cov(x,y):
    s = 0
    mu_x = sum(x)/len(x)
    mu_y = sum(y)/len(x)
    for i in range(len(x)):
        s += (x[i] - mu_x)*(y[i] - mu_y)
    return s/len(x)

In [39]:
cov(x,y)

2.5

Once again we can rescale the covariance function with $N-1$, $\text{cov}(x,y)=\frac{1}{N-1}\sum_{i=1}^N (x_i-\mu_x)(y_i-\mu_y)$, to get the result with no bias.

In [40]:
def cov(x,y):
    s = 0
    mu_x = sum(x)/len(x)
    mu_y = sum(y)/len(x)
    for i in range(len(x)):
        s += (x[i] - mu_x)*(y[i] - mu_y)
    return s/(len(x)-1)

In [41]:
cov(x,y)

3.3333333333333335

# Covariance matrix function

We can find the covariance matrix now by using the definition of the covariance function

In [42]:
c = np.zeros((len(data),len(data)))
for i in range(len(data)):
    for j in range(len(data)):
        c[i,j] = cov(data[i], data[j])
print(c)

[[ 1.66666667  3.33333333 -1.66666667]
 [ 3.33333333  6.66666667 -3.33333333]
 [-1.66666667 -3.33333333  1.66666667]]


These results match the results from the numpy package.

# Making covariance matrix for random data

In [58]:
rng = np.random.RandomState(1) # seed 
X = np.dot(rng.rand(2, 2), rng.randn(2, 200))
# print(X)
print(np.shape(X)) # (2, 200) means we have 2 rows and 200 columns

(2, 200)


In [89]:
Xm = np.mean(X, axis=1) # mean
Xs = np.std(X, axis=1) # standard deviation
Xv = np.var(X, axis=1) # variance
print(Xm)
print(Xs)
print(Xv)

[ 0.03351168 -0.00408072]
[0.823873   0.31358832]
[0.67876672 0.09833763]


In [90]:
Xn = ((X.T-Xm.T)/Xs.T).T # standardization
print(np.mean(Xn, axis=1)) # mean
print(np.std(Xn, axis=1)) # standard deviation
print(np.var(Xn, axis=1))

[-3.10862447e-17  0.00000000e+00]
[1. 1.]
[1. 1.]


In [91]:
c = np.zeros((len(Xn), len(Xn)))
for i in range(len(Xn)):
    for j in range(len(Xn)):
        c[i,j] = cov(Xn[i], Xn[j])
print(c)

[[1.00502513 0.89385925]
 [0.89385925 1.00502513]]


In [94]:
np.cov(Xn)

array([[1.00502513, 0.89385925],
       [0.89385925, 1.00502513]])