In [2]:
x = [1,2,3,4]
y = [2,4,6,8]
z = [10,9,8,7]
data = [x,y,z]

In [3]:
data

[[1, 2, 3, 4], [2, 4, 6, 8], [10, 9, 8, 7]]

In [32]:
import numpy as np
print(np.cov(data, bias=True))

[[ 1.25  2.5  -1.25]
 [ 2.5   5.   -2.5 ]
 [-1.25 -2.5   1.25]]


In [6]:
def var(x):
    s = 0
    mu = sum(x)/len(x)
    for i in range(len(x)):
        s += (x[i] - mu)**2
    return s/len(x)

In [11]:
var(z)

1.25

In [15]:
def cov(x,y):
    s = 0
    mu_x = sum(x)/len(x)
    mu_y = sum(y)/len(x)
    for i in range(len(x)):
        s += (x[i] - mu_x)*(y[i] - mu_y)
    return s/len(x)

In [16]:
cov(x,y)

2.5

In [34]:
c = np.zeros((len(data),len(data)))
for i in range(len(data)):
    for j in range(len(data)):
        c[i,j] = cov(data[i], data[j])
c

array([[ 1.25,  2.5 , -1.25],
       [ 2.5 ,  5.  , -2.5 ],
       [-1.25, -2.5 ,  1.25]])

We dont quite the results we are after. Will try different data to see if we get better results

In [22]:
rng = np.random.RandomState(1)
X = np.dot(rng.rand(2, 2), rng.randn(2, 200)).T

In [35]:
Xm = np.mean(X)
Xs = np.std(X)
Xv = np.var(X)

In [36]:
Xn = (X-Xm)/Xs

In [ ]:
ok so it appears using normalized data produces correct results

In [49]:
data=np.array(data)
Xm = np.mean(data.T, axis=0)
Xs = np.std(data.T, axis=0)
Xv = np.var(data.T, axis=0)
Xn = (data.T-Xm)/Xs
Xn

array([[-1.34164079, -1.34164079,  1.34164079],
       [-0.4472136 , -0.4472136 ,  0.4472136 ],
       [ 0.4472136 ,  0.4472136 , -0.4472136 ],
       [ 1.34164079,  1.34164079, -1.34164079]])

In [ ]:
c = np.zeros((len(data), len(data)))
for i in range(len(Xn)):
    for j in range(len(Xn)):
        c[i,j] = cov(Xn[i], Xn[j])
c